is_heart_patient(id_85).
is_heart_patient(id_86).
is_heart_patient(id_87).
is_heart_patient(id_88).
is_heart_patient(id_89).
is_heart_patient(id_90).
is_heart_patient(id_91).
is_heart_patient(id_91).
is_heart_patient(id_93).
is_heart_patient(id_94).
is_heart_patient(id_95).
is_heart_patient(id_96).
is_heart_patient(id_97).
is_heart_patient(id_98).
is_heart_patient(id_99).
is_heart_patient(id_100).