is_heart_patient(id_0).
is_heart_patient(id_1).
is_heart_patient(id_2).
is_heart_patient(id_3).
is_heart_patient(id_4).
is_heart_patient(id_5).
is_heart_patient(id_6).
is_heart_patient(id_7).
is_heart_patient(id_8).
is_heart_patient(id_9).
is_heart_patient(id_10).
is_heart_patient(id_11).
is_heart_patient(id_12).
is_heart_patient(id_13).
is_heart_patient(id_14).
is_heart_patient(id_15).
is_heart_patient(id_16).
is_heart_patient(id_17).
is_heart_patient(id_18).
is_heart_patient(id_19).
is_heart_patient(id_20).