is_heart_patient(id_37).
is_heart_patient(id_38).
is_heart_patient(id_39).
is_heart_patient(id_40).
is_heart_patient(id_41).
is_heart_patient(id_42).
is_heart_patient(id_43).
is_heart_patient(id_44).
is_heart_patient(id_45).
is_heart_patient(id_46).
is_heart_patient(id_47).
is_heart_patient(id_48).
is_heart_patient(id_49).
is_heart_patient(id_50).
is_heart_patient(id_51).
is_heart_patient(id_52).
